### ISSUE TITLE
[Bug] Unable to attach a lot of files simultaneously

### ISSUE THREAD

**Issue by djarkobobanov** [rootstrap/active-storage-base64#58]
## Bug report:
* **Expected Behavior**:  
Hi, I'm having an issue when trying to upload a lot of pdfs (30 files to be exact) with total size of 37MB and each files under 10MB, it's expected for the attachments to be attached to the transaction after it has been submitted. do you guys have any suggestions? thank you very much for this beatiful gem btw

this is the model: 
```ruby
class BusinessTransaction < ApplicationRecord
  include Rails.application.routes.url_helpers
  has_one_base64_attached :receipt
  has_many_base64_attached :invoices
  validates :receipt, presence: false, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf'], size_range: 1..10.megabytes }
  validates :invoices, presence: false, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf'], size_range: 1..10.megabytes }
end
```

and this is the controller:
```ruby
class Api::V1::BusinessTransactionsController < Api::ApplicationController

  def create_single_transaction
    @business_transaction = BusinessTransaction.new(business_transaction_params)
    if @business_transaction.save
        render json: {status: 200, data: @business_transaction.as_json}
    else
      render json: {status: 422, message: @business_transaction.errors}, status: 422
    end
  end

  private
  def business_transaction_params
      params.permit( :receipt => :data, invoices: [:data, :filename], sender:{}, beneficiary:{}, compliance:{}, :partner_bank_account_attributes =>{})
  end

end
```
* **Actual Behavior**: 
It returns this error in the middle of processing the base64 data `NoMethodError: undefined method 'unpack1' for nil:NilClass`
* **Steps to Reproduce**: 
  1. attach a lot of files (via react/postman using base64)
  2. submit the files

* **Version of the repo**: I'm using `active_storage_base64 (0.1.4)`
* **Ruby and Rails Version**: ruby => ruby 2.6.3p62, rails => rails (~> 5.2.4)

**Comment by Ricoch** [comment]
Hey @djarkobobanov! Let me try to help you debug here
Can you show me an example of a JSON you are trying to send? Please exclude the base64 data, just the format

**Comment by Ricoch** [comment]
Also, a couple of questions:
Does this only happen when you try to upload 30 files for a size of 37mb? Or it also happens when you try to do it with 3 files for about 6mb?

**Comment by djarkobobanov** [comment]
Thank you for you fast response, regarding the first question here is the JSON request :

```json
{
   "invoices":[
      {
         "data":"BASE64STRING",
         "filename":"y.pdf"
      },
      {
         "data":"BASE64STRING",
         "filename":"x.pdf"
      }
   ]
}
```

and for the second question, it works perfectly if i try to upload 3 files for 6mb even with smaller/less than 20 files. it only happens if i upload a huge amount of files simultaneously

**Comment by Ricoch** [comment]
JSON structure looks perfectly fine to me so let's discard that.

Do you have an extended stack trace you can show me? From your error, I deduct the issue is coming from here: 
https://github.com/rootstrap/active-storage-base64/blob/v0.1.4/lib/active_storage_support/base64_attach.rb#L19 , is this assumption correct? Is there any chance one of the files base64 is corrupted?

I would try to do the following on your terminal:
`$ export EDITOR=vim`
`$ bundle open active_storage_base64`
`lib > active_storage_support > base64_attach.rb` and add a debugger there before trying to decode just to make sure it's not a data issue, I would do something like:
```ruby
unless data
  binding.pry / byebug
end  
```
If my assumption is correct and the issue is indeed in that line, then we might be able to caught the issue that way. If you get the breakpoint to get hit, we can check the `base64_data` arriving

**Comment by Ricoch** [comment]
Hey @djarkobobanov wondering if you were able to sort the issue or you are still experiencing this?
